repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-ast
    stages: [commit]

- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
  - id: black
    stages: [commit]
    language_version: python3.11

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    stages: [commit]

- repo: local
  hooks:
  - id: unit-tests
    name: Unit tests
    stages: [push]
    entry: bash -c "cd backend && bin/test"
    additional_dependencies:
      - Flask
      - flask-sqlalchemy
      - pytest
      - pytest-cov
      - pytest-mock
    language: python
  - id: sonar
    name: sonar-scanner
    stages: [push]
    entry: bash -c "docker-compose run --no-TTY sonar-scanner-cloud"
    language: system
