name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  backend-pytest-tests:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update environment
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update -y
          sudo apt-get install python3.11
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          cd backend
          poetry install --no-interaction --no-root

      - name: Run pytest unit tests
        run: |
          cd backend
          poetry run bin/test
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          CSRF_SECRET_KEY: ${{ secrets.CSRF_SECRET_KEY }}

      - name: Upload pytest test report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-coverage-report
          path: backend/coverage/coverage.xml

  frontend-jest-tests:
    name: jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '19.5.0'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run jest unit tests
        run: |
          cd frontend
          npm run test

      - name: Upload jest test report
        uses: actions/upload-artifact@v3
        with:
          name: jest-coverage-report
          path: frontend/coverage/lcov.info

  sonarcloud:
    name: SonarCloud
    needs: [backend-pytest-tests, frontend-jest-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Download pytest test report
        uses: actions/download-artifact@v3
        with:
          name: pytest-coverage-report
          path: backend/coverage/

      - name: Normalize source path in pytest test report
        run: |
          sed -i "s/<source>.*\/app/<source>\/github\/workspace/g" backend/coverage/coverage.xml

      - name: Download jest test report
        uses: actions/download-artifact@v3
        with:
          name: jest-coverage-report
          path: frontend/coverage/

      - name: Normalize source path in pytest test report
        run: |
          sed -i "s/SF:src/SF:\/github\/workspace\/frontend\/src/g" frontend/coverage/lcov.info

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
